version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ClockworkChronicle
    restart: always
    environment:
      POSTGRES_DB: chronicle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "4500:5432"